### ISSUE TITLE
`get_assignment` function fetches assignments from all questionnaires if version is not defined.

### ISSUE THREAD

**Issue by ashwinikalantri** [arthur-shaw/susoapi#27]
In the `get_assignment` function, the expected function if `qnr_version` argument is not defined should be to get all assignments of the questionnaire defined in the `qnr_id` argument. Instead, this fetches all the assignments from all the questionnaires in the defined workspace.

**Comment by arthur-shaw** [comment]
I like @petbrueck 's first proposed solution: checking that `qnr_version` is provided and is valid. @ashwinikalantri , @petbrueck , would that be OK? 

Another complementary question: do you see any compelling reason to migrate to GraphQL for fetching assignment details? My answer is "no". The REST API provides a few things GraphQL doesn't: number of interviews collected, update date, whether expect audio recording, questionnaire ID and version,  and perhaps other things I've missed. The GraphQL version contains details on the [calendar events](https://docs.mysurvey.solutions/release-notes/version-20-12/). But I'm very open to other views.

Note: I'm currently preparing a new release of `{susoapi}` that will tackle a few big tickets (e.g., #24 , #26 , #23 ) and bug fixes--among them this one.

**Comment by ashwinikalantri** [comment]
I agree that checking `qnr_version` will ensure not getting unexpected assignments.

On the other hand, getting all assignments of a questionnaire using a single function could be useful. Otherwise we have to loop the function for all the versions and then combine them. It may be better to have the function handle this.

**Comment by arthur-shaw** [comment]
I'll think about this a bit more, but here's my current inclination:

- Have `susoapi::get_assignments` return assignments for only one questionnaire-version pair. In other words, have the function be a thin wrapper around the endpoint
- Provide a function in `{susoflows}` that returns assignments for all versions of a questionnaire, since that package handles workflows of this type (e.g., download data for all versions of a questionnaire).
