### ISSUE TITLE
install susoapi

### ISSUE THREAD

**Issue by sakurita17** [arthur-shaw/susoapi#32]
Hello @arthur-shaw , what if Rtools seems to be that is installed but is not part of the environment variables?
![image](https://user-images.githubusercontent.com/79160277/177407064-1bb49352-50fa-40e6-96f8-b91cf98d99c5.png)

**Comment by sakurita17** [comment]
Hello @arthur-shaw , I had to use an old R´s version and untick the mark on using the secure download method HTTP. Additionally, I selected Global (CDN) as the primary CRAN repository.

**Comment by arthur-shaw** [comment]
@sakurita17 , thanks for the response here and on the Survey Solutions forum [here](https://forum.mysurvey.solutions/t/problem-susoapi/4813). 

A few follow-up questions:

1. What was the CRAN resposity before you changed it to `Global (CDN) - RStudio`?
2. Did your problem persist if you kept `Use secure download method for HTTP` ticked?
3. Am I right that you had to use R < 4.2 in order to get `susoapi` to install on your machine?
4. If so, do you have RTools installed for R < 4.2? To answer that question, could you please send me the output of:
```
# check whether RTools is installed
pkgbuild::find_rtools(debug = TRUE)
pkgbuild::r

# find where RTools is installed
pkgbuild::rtools_path()

# determine whether RTools is part of the environment variables
grepl(
    x = Sys.getenv("PATH"), 
    pattern = "[Rr]tools"
)
```

For R 4.2, I'm not as familiar with the RTools installation. To replicate your problem, I'll install R 4.2 on another device. (Currently, I'm running R 4.1.1.)
